### ISSUE TITLE
New page /artists

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2019.cssconf.eu#109]
In order to showcase the artists contributing to the event, we need a new page `/artists`.

Analogous to https://2019.jsconf.eu/artists/

**Comment by Kriesse** [comment]
@cramforce Just double-checking, artists are the same on all three days, correct?
We can use the same info as here?
https://2019.jsconf.eu/artists/

**Comment by cramforce** [comment]
@Kriesse And you can just copy the same data from the CMS spreadsheet if you'd like
https://github.com/jsconf/festival-x.jsconf.eu/pull/129
