### ISSUE TITLE
Improve visibility of bipocit space and community lounge (speakers and schedules)

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2019.cssconf.eu#120]
- [ ] add to main navigation?
or
- [ ] add as tabs on main  /schedule and /speakers pages?

**Comment by lukaszklis** [comment]
We should definitely link to speaker pages from the schedule

**Comment by Kriesse** [comment]
also related to https://github.com/cssconf/2019.cssconf.eu/issues/107

**Comment by lukaszklis** [comment]
Fixed in #131.
