### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2019.cssconf.eu#35]
- [x] create page
- [x] add content (for questions like: how can I speak? can I volunteer? pronouns?…)

**Comment by Lucie-H** [comment]
@Kriesse Where do I actually get the content from? 😅 Do we have a list or something?

**Comment by Kriesse** [comment]
@Lucie-H I have on my inner list the following:
- How can I become a speaker? --> Link to cfs
- How can I become a sponsor? --> email us
- Why am I asked to select my pronouns when buying a ticket? --> see Thuys answer in Slack
- Can I volunteer? --> email us

We can add more as we go and receive questions :)

**Comment by cramforce** [comment]
We should use our new "CMS" to manage the content of this. We then only need to add an item to the Navigation when the content is in.

**Comment by lukaszklis** [comment]
Closing since it’s already done: https://2019.cssconf.eu/faq/
