### ISSUE TITLE
Create a page about BIPOCiT space

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2019.cssconf.eu#62]
@1000miles We would like to have a page on the CSSconf website where we explain the space (and later on, publish a program, information how to contribute, or whatever else you might need and want to publish).

Could you provide us with content?

**Comment by 1000miles** [comment]
Hi there, yes, that is on our plate. I will take care of this with the others in our team. Thanks for creating this issue. 

@ TODO

- [ ] Create text content for the `QTI.BPOC space`
   - [ ] Intro => Why this space and what is it about?
   - [ ] Program will follow at a later time
- [ ] Add members of the `QTI.BIPOC space` to team page (we decided to have a clear line between community lounge & QTI.BIPOC space to avoid people mixing up these 2 spaces)

**Comment by cramforce** [comment]
The content can be in a Google Doc. All we need to do in the repo here is
add a link. And we should copy the doc for JSConf.

Showing the team (maintained through the team spreadsheet) needs a little
bit of programming.

**Comment by 1000miles** [comment]
FYI, @laurendorman, @DeraLuce, @Vinesse and me decided on a new name today : `BIPOCiT` (Black, Indigenous and People of Color in Tech). :)

I will change the ticket title now. A proper text will follow.

**Comment by 1000miles** [comment]
Points we want to consider when creating the text:
- the name is not invented by us but is a result of all previous and on-going discussions of other groups that came before us
- we were inspired by the great initiative of `POCIT` (People of Color in Tech) - https://peopleofcolorintech.com
- we do not tolerate any kind of phobia (especially against QTIBIPOC & LGBTQIA+), racism, anti-Semitism, anti-Muslim or anti-Blackness, etc.

**Comment by lukaszklis** [comment]
Done in https://2019.cssconf.eu/bipocit-space/
