### ISSUE TITLE
Create a page /community-lounge

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2019.cssconf.eu#63]
@sheley We would like to have a page on the CSSconf website where we explain the Community Lounge (and later on, publish a program, information how to contribute, or whatever else you might need and want to publish).

Could you provide us with content?

**Comment by cramforce** [comment]
The content can be in a Google Doc. All we need to do in the repo here is
add a link. And we should copy the doc for JSConf.

**Comment by Kriesse** [comment]
@cramforce Would @sheley (and, moving forward, potential website or content volunteers) have access to the Google Doc? If not, I'd prefer to keep the content in the repo.

Personally I find editing content in the repo easier (because it can be done offline which is handy e.g. on planes, and I know where to look for it), but happy to oblige to what works best for everyone!

**Comment by cramforce** [comment]
The doc can have more liberal access and works offline as well. In practice
it is much more agile. Especially if you want to just make a few edits and
not bother getting a local install up and running.

**Comment by Kriesse** [comment]
sounds good 👍

**Comment by lukaszklis** [comment]
Done in https://2019.cssconf.eu/community-lounge/
